### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by jacksun101** [vdlp/oc-telescope-plugin#3]
During installation process, I met this issue. And I have an active theme. Any suggestion?

```
php artisan vendor:publish --tag telescope-assets --force

Unable to locate publishable resources.
Publishing complete.
```

**Comment by sander-beenen** [comment]
The assets and configuration can only be published if Telescope is enabled. Do you have `TELESCOPE_ENABLED = false` in your `.env` file or `'enabled' => false,` in `config/telescope.php`?
